# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  format:
    runs-on: ubuntu-latest
    name: terraform-format-action
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        
      - name: Format terraform code
        run: terraform fmt -check=true -diff --recursive
        
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - uses: actions/checkout@v2
      
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .


          quiet: true # optional: display only failed checks
